version: 2.1

orbs:
  go-module: timakin/go-module@0.3.0
  heroku: circleci/heroku@0.0.8
  github-release: izumin5210/github-release@0.1.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sue445/gitpanda
    environment:
      GO111MODULE: "on"

jobs:
  test:
    executor: golang

    steps:
      - attach_workspace:
          at: /go/src/github.com/sue445/gitpanda
      - restore_cache:
          key: go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}
      - run:
          command: go test

  golint:
    executor: golang

    steps:
      - attach_workspace:
          at: /go/src/github.com/sue445/gitpanda
      - run:
          command: go get -u golang.org/x/lint/golint
      - run:
          command: golint -set_exit_status

  go-vet:
    executor: golang

    steps:
      - attach_workspace:
          at: /go/src/github.com/sue445/gitpanda
      - run:
          command: go vet

  gox:
    executor: golang

    steps:
      - checkout
      - run:
          command: go get -u github.com/mitchellh/gox
      - run:
          command: make gox
      - persist_to_workspace:
          root: /go/src/github.com/sue445/gitpanda
          paths:
            - .

workflows:
  build-and-deploy:
    jobs:
      - go-module/download:
          executor: golang
          persist-to-workspace: true

      - test:
          requires:
            - go-module/download

      - golint:
          requires:
            - go-module/download

      - go-vet:
          requires:
            - go-module/download

      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - test
            - golint
            - go-vet
          filters:
            branches:
              only: master

  release:
    jobs:
      - gox:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

      - github-release/create:
          executor: golang
          path: ./bin/
          requires:
            - gox
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
