version: 2.1

orbs:
  go-module: timakin/go-module@0.3.0

executors:
  golang:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sue445/gitpanda
    environment:
      GO111MODULE: "on"

jobs:
  test:
    executor: golang

    steps:
      - attach_workspace:
          at: /go/src/github.com/sue445/gitpanda
      - restore_cache:
          key: go-mod-cache-{{ .Branch }}-{{ checksum "go.sum" }}
      - run:
          command: go test

  golint:
    executor: golang

    steps:
      - attach_workspace:
          at: /go/src/github.com/sue445/gitpanda
      - run:
          command: go get -u golang.org/x/lint/golint
      - run:
          command: golint -set_exit_status

  go-vet:
    executor: golang

    steps:
      - attach_workspace:
          at: /go/src/github.com/sue445/gitpanda
      - run:
          command: go vet

workflows:
  build:
    jobs:
      - go-module/download:
          executor: golang
          persist-to-workspace: true

      - test:
          requires:
            - go-module/download

      - golint:
          requires:
            - go-module/download

      - go-vet:
          requires:
            - go-module/download
